apiVersion: v1
kind: Pod
metadata:
  name: api-server
  labels:
    app: api-server
spec:
  containers:
  - name: api-server
    image: 149095730232.dkr.ecr.eu-central-1.amazonaws.com/jenkins-x:jenkins-x-nodejs-api-server-v4
    ports:
      - containerPort: 3000
        name: api-server-port
